import { motion } from "framer-motion";
import {
  AlertTriangle,
  BrainCircuit,
  Lightbulb,
  TrendingUp,
} from "lucide-react";

interface InsightsSectionProps {
  insights: string;
}

export default function InsightsSection({ insights }: InsightsSectionProps) {
  if (!insights) return null;

  // Parse insights into bullet points if possible
  const insightPoints = insights.includes("\n")
    ? insights.split("\n").filter((point) => point.trim().length > 0)
    : [insights];

  return (
    <div>
      {/* Insights List */}
      <div className='space-y-4'>
        {insightPoints.map((insight, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 * index }}
            className='bg-gradient-to-br from-blue-50/70 to-indigo-50/70 dark:from-blue-900/20 dark:to-indigo-900/20 backdrop-blur-sm border border-blue-100/30 dark:border-blue-800/30 rounded-xl p-5 hover:shadow-md transition-all duration-300'
          >
            <div className='flex'>
              <div className='flex-shrink-0 mr-4'>
                <div className='p-2 rounded-lg bg-white/70 dark:bg-slate-800/70 text-blue-600 shadow-sm'>
                  {index % 3 === 0 ? (
                    <Lightbulb className='w-5 h-5' />
                  ) : index % 3 === 1 ? (
                    <TrendingUp className='w-5 h-5' />
                  ) : (
                    <AlertTriangle className='w-5 h-5' />
                  )}
                </div>
              </div>
              <div>
                <p className='text-gray-700 dark:text-gray-300 leading-relaxed'>
                  {insight}
                </p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* AI Attribution */}
      <div className='mt-4 text-center'>
        <div className='inline-flex items-center space-x-2 bg-gradient-to-r from-blue-500/10 to-purple-500/10 backdrop-blur-sm border border-white/20 rounded-full px-4 py-1'>
          <BrainCircuit className='h-3 w-3 text-purple-500' />
          <span className='text-xs font-medium text-gray-600 dark:text-gray-400'>
            Generated by AI based on your data patterns
          </span>
        </div>
      </div>
    </div>
  );
}
